services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env.config
      - .env.secrets
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:7.2.5"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  
  mongo:
    image: "mongo:7.0.12"
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
