services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
      - .env.secrets
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: "redis:7.2.5"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
