services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
      - .env.secrets
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:7.2.5"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"